<?php

namespace core\modules\user\models;

use Yii;
use core\components\ActiveRecord;
use yii\behaviors\TimestampBehavior;
use yii\db\BaseActiveRecord;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "tbl_user_payments".
 *
 * @property int $id
 * @property string $type
 * @property string $system
 * @property double $money
 * @property string $name
 * @property string $data
 * @property string $status
 */
class Payments extends ActiveRecord
{
    public static function getDb()
    {
        return Yii::$app->serverDb;
    }

    const MODULE_ID = 'user';
    const route = '/admin/user/default';

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return "{{%user_payments}}";
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        // set initial rules
        $rules = [
            // general email and username rules
            [['system', 'name'], 'string', 'max' => 255],
            //[['email'], 'unique'],
            //[['email'], 'filter', 'filter' => 'trim'],

        ];

        return $rules;
    }

    public function beforeSave($insert)
    {
        $this->user_id = Yii::$app->user->id;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
       // $this->_user = User::findIdentity($this->user_id);
        //$this->_user->money += $this->money;
        //$this->_user->save(false);
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }


    public function behaviors()
    {


//operations
        return [
            'timestamp' => [
                'class' => TimestampBehavior::class,
                'attributes' => [
                    BaseActiveRecord::EVENT_BEFORE_INSERT => ['created_at'],
                ]
            ]
        ];
    }
}
